name: meta
description: Domain for interacting with Bitspark nodes.
permissions:
  view:
    public: true
types: []
interfaces:
    - name: Node
      description: Represents a Bitspark node.
      hubs:
        - description: Creates a new system on the node.
          direction: in
          input:
            - name: blueprint
              description: Blueprint from which the system should be created.
              value: $hub.blueprint
          name: createSystem
          output:
            - name: system
              description: System created from the blueprint.
              value: $hub.system
          type: pipe
        - description: Adds a system to the node.
          direction: in
          input:
            - name: system
              description: System to add to the node.
              value: $hub.system
          name: addSystem
          output:
            - name: system
              description: System attached to the node.
              value: $hub.system
          type: pipe
        - description: Returns the systems on this node.
          direction: in
          input: []
          name: getSystems
          output:
            - name: system
              value:
                - reference: hub.system
          type: pipe
        - description: Returns the number of systems on this node.
          direction: in
          input: []
          name: getSystemCount
          output:
            - name: count
              value: integer
          type: pipe
        - description: Returns the connected nodes of this node.
          direction: in
          input: []
          name: getNodes
          output:
            - name: nodes
              value:
                - reference: hub.system
          type: pipe
        - description: Returns the addresses for different networks of this node.
          direction: in
          input: []
          name: getAddresses
          output:
            - name: addresses
              value:
                listOf:
                  mapOf:
                    network:
                      leaf: string
                    address:
                      leaf: string
          type: pipe
        - description: Sets the address of this node for a network.
          direction: in
          input:
            - name: network
              description: Network of the address.
              value:
                leaf: string
            - name: address
              description: The address.
              value:
                leaf: string
          name: setAddress
          output: []
          type: pipe
blueprints:
    - name: Node
      description: Represents a Bitspark node providing a runtime environment for systems.
      constructor: []
      interface:
        extends:
            - Node
      implementation:
        node: [{}]
models: []
